# Vets Service (PetclinicPlatform41). ClusterIP on 8081.
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  labels:
    app.kubernetes.io/name: vets-service
    app.kubernetes.io/component: vets-service
    app.kubernetes.io/part-of: petclinic
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vets-service
  ports:
    - name: http
      port: 8083
      targetPort: http
