# Admin Server (PetclinicPlatform43). ClusterIP on 8080.
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  labels:
    app.kubernetes.io/name: admin-server
    app.kubernetes.io/component: admin-server
    app.kubernetes.io/part-of: petclinic
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: admin-server
  ports:
    - name: http
      port: 9090
      targetPort: http
