apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visits-service-prod
  namespace: argocd
  labels:
    project: petclinic
    environment: prod
spec:
  project: default
  source:
    repoURL: https://github.com/ukpabi-Joy/-petclinic-platform.git
    targetRevision: main
    path: helm/petclinic-service
    helm:
      releaseName: visits-service
      valueFiles:
        - ../../helm-values/visits-service.yaml
        - ../../helm-values/prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-prod
  syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
