locals {
  name        = "${var.project}-${var.environment}"
  secret_name = "${var.project}/${var.environment}/db-credentials"
}

# ---------------------------------------------------------------------------
# Master password — generated by Terraform, never committed to Git.
# RDS disallows '/', '@', '"' and spaces in the master password.
# ---------------------------------------------------------------------------
resource "random_password" "master" {
  length           = 24
  special          = true
  override_special = "!#$%^&*()-_=+[]{}<>:?"
}

# ---------------------------------------------------------------------------
# Networking — subnet group spanning the VPC subnets (multiple AZs).
# ---------------------------------------------------------------------------
resource "aws_db_subnet_group" "this" {
  name       = "${local.name}-db"
  subnet_ids = var.subnet_ids

  tags = {
    Name = "${local.name}-db"
  }
}

# ---------------------------------------------------------------------------
# Parameter group — MySQL 8.0 with custom settings.
# ---------------------------------------------------------------------------
resource "aws_db_parameter_group" "this" {
  name        = "${local.name}-mysql80"
  family      = var.parameter_group_family
  description = "Custom MySQL 8.0 parameters for ${local.name}"

  dynamic "parameter" {
    for_each = var.db_parameters
    content {
      name  = parameter.value.name
      value = parameter.value.value
    }
  }

  tags = {
    Name = "${local.name}-mysql80"
  }

  lifecycle {
    create_before_destroy = true
  }
}

# ---------------------------------------------------------------------------
# Database instance.
# ---------------------------------------------------------------------------
resource "aws_db_instance" "this" {
  identifier = "${local.name}-mysql"

  engine         = "mysql"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage = var.allocated_storage
  storage_type      = var.storage_type
  storage_encrypted = var.storage_encrypted
  kms_key_id        = var.kms_key_arn

  db_name  = var.db_name
  username = var.username
  password = random_password.master.result
  port     = var.port

  multi_az               = var.multi_az
  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = var.vpc_security_group_ids
  parameter_group_name   = aws_db_parameter_group.this.name

  # Never reachable from the public internet — access is via the EKS node SG only.
  publicly_accessible = false

  backup_retention_period = var.backup_retention_period
  deletion_protection     = var.deletion_protection
  skip_final_snapshot     = var.skip_final_snapshot
  final_snapshot_identifier = (
    var.skip_final_snapshot ? null : "${local.name}-mysql-final"
  )

  apply_immediately = true

  tags = {
    Name = "${local.name}-mysql"
  }
}

# ---------------------------------------------------------------------------
# Secrets Manager — credentials + connection details for consumers (ESO etc.).
# ---------------------------------------------------------------------------
resource "aws_secretsmanager_secret" "db" {
  name                    = local.secret_name
  description             = "MySQL credentials and connection details for ${local.name}"
  recovery_window_in_days = var.secret_recovery_window_days

  tags = {
    Name = local.secret_name
  }
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id

  secret_string = jsonencode({
    username = var.username
    password = random_password.master.result
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
    dbname   = var.db_name
  })
}
