image:
  repository: config-server
  tag: "4546733"

service:
  port: 8888
  targetPort: http
  portName: http

containerPort: 8888

probes:
  startup:
    path: /actuator/health
    initialDelaySeconds: 0
    periodSeconds: 10
    failureThreshold: 30
  readiness:
    path: /actuator/health
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    path: /actuator/health
    initialDelaySeconds: 20
    periodSeconds: 15
    failureThreshold: 3
