apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discovery-server-dev
  namespace: argocd
  labels:
    project: petclinic
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/ukpabi-Joy/-petclinic-platform.git
    targetRevision: main
    path: helm/petclinic-service
    helm:
      releaseName: discovery-server
      valueFiles:
        - ../../helm-values/discovery-server.yaml
        - ../../helm-values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
